### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by bluce-clj** [nixzhu/Sensei#1]
Sensei main % make sensei bundle-id-prefix=io.tuist version=0.3.0 build=10
tuist fetch
Version 3.17.0 not found locally. Installing...
Downloading version 3.17.0
Installing…
Version 3.17.0 installed
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: 'swiftpackagemanager': package 'swiftpackagemanager' is using Swift tools version 5.8.0 but the installed version is 5.7.1
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
make: *** [sensei] Error 1

Sensei main % make sensei bundle-id-prefix=io.tuist version=0.3.0 build=10
tuist fetch
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: 'swiftpackagemanager': package 'swiftpackagemanager' is using Swift tools version 5.8.0 but the installed version is 5.7.1
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
make: *** [sensei] Error 1

**Comment by nixzhu** [comment]
@bluce-clj Do you use Xcode 14.3 as your Command Line Tools?

**Comment by bluce-clj** [comment]
I'm use Version 14.2 (14C18),So need update version to 14.3?

**Comment by nixzhu** [comment]
@bluce-clj Yes. Or you can use `tuist edit` to modify the settings of the project.
